# Generated by Django 5.0.4 on 2024-09-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_documents_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbots',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbots',
            name='model_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('advanced', 'Advanced')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='chatbots',
            name='prompt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chatbots',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
